[package]
name = "nt-hive"
version = "0.1.0"
authors = ["Colin Finck <colin@reactos.org>"]
edition = "2018"
license = "GPL-2.0-or-later"
keywords = ["windows", "nt", "registry", "hive", "regf", "no_std"]

[dependencies]
bitflags = "1.2.1"
byteorder = { version = "1.3.4", default-features = false }
displaydoc = { version = "0.1.7", default-features = false }
memoffset = "0.6.1"
num_enum = { version = "0.5.1", default-features = false }
zerocopy = "0.3.0"

[features]
default = ["std"]
alloc = []
std = ["alloc"]
